// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_main
void ui_main_screen_init(void);
extern lv_obj_t * ui_main;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_TabView3;
extern lv_obj_t * ui_Temperature;
extern lv_obj_t * ui_Chart1;
extern lv_obj_t * ui_Humidity;
extern lv_obj_t * ui_Chart2;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Dropdown1;
extern lv_obj_t * ui_Water;
extern lv_obj_t * ui_Temp;
extern lv_obj_t * ui_HumLebal;
extern lv_obj_t * ui_TempLebal;
void ui_event_Button11(lv_event_t * e);
extern lv_obj_t * ui_Button11;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Label1;
void ui_event_Button12(lv_event_t * e);
extern lv_obj_t * ui_Button12;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Label18;
void ui_event_Button13(lv_event_t * e);
extern lv_obj_t * ui_Button13;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Label3;
// SCREEN: ui_kongtiao
void ui_kongtiao_screen_init(void);
void ui_event_kongtiao(lv_event_t * e);
extern lv_obj_t * ui_kongtiao;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_sheshidu;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Arc1;
void ui_event_chushi(lv_event_t * e);
extern lv_obj_t * ui_chushi;
extern lv_obj_t * ui_Label12;
void ui_event_shengdian(lv_event_t * e);
extern lv_obj_t * ui_shengdian;
extern lv_obj_t * ui_Label14;
void ui_event_zhileng(lv_event_t * e);
extern lv_obj_t * ui_zhileng;
extern lv_obj_t * ui_Label15;
void ui_event_zhire(lv_event_t * e);
extern lv_obj_t * ui_zhire;
extern lv_obj_t * ui_Label16;
void ui_event_zidong(lv_event_t * e);
extern lv_obj_t * ui_zidong;
extern lv_obj_t * ui_Label21;
void ui_event_shuimian(lv_event_t * e);
extern lv_obj_t * ui_shuimian;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Dropdown3;
void ui_event_TempIncrease(lv_event_t * e);
extern lv_obj_t * ui_TempIncrease;
extern lv_obj_t * ui_Label8;
void ui_event_TempDecrease(lv_event_t * e);
extern lv_obj_t * ui_TempDecrease;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_moshi;
extern lv_obj_t * ui_fengsu;
extern lv_obj_t * ui_fengxiang;
extern lv_obj_t * ui_moshiNum;
extern lv_obj_t * ui_Roller1;
extern lv_obj_t * ui_Roller3;
// SCREEN: ui_DengGuang
void ui_DengGuang_screen_init(void);
void ui_event_DengGuang(lv_event_t * e);
extern lv_obj_t * ui_DengGuang;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Dropdown4;
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_Slider1;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_Image14;
extern lv_obj_t * ui_Slider3;
extern lv_obj_t * ui_Image11;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_Image12;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Label26;
// SCREEN: ui_AirQuality
void ui_AirQuality_screen_init(void);
void ui_event_AirQuality(lv_event_t * e);
extern lv_obj_t * ui_AirQuality;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Label33;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_Water2;
extern lv_obj_t * ui_TempLebal2;
extern lv_obj_t * ui_TempLabel2;
extern lv_obj_t * ui_HumLabel2;
extern lv_obj_t * ui_Container7;
extern lv_obj_t * ui_Arc2;
extern lv_obj_t * ui_Arc3;
extern lv_obj_t * ui_Arc4;
extern lv_obj_t * ui_Arc5;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_Label30;
extern lv_obj_t * ui_Label31;
extern lv_obj_t * ui_Label32;
extern lv_obj_t * ui_Label34;
extern lv_obj_t * ui_TabView2;
extern lv_obj_t * ui_Temperature2;
extern lv_obj_t * ui_Chart5;
extern lv_obj_t * ui_Humidity2;
extern lv_obj_t * ui_Chart3;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_router_png);    // assets/Router.png
LV_IMG_DECLARE(ui_img_water_png);    // assets/water.png
LV_IMG_DECLARE(ui_img_temperature_png);    // assets/Temperature.png
LV_IMG_DECLARE(ui_img_kongtiao_png);    // assets/Kongtiao.png
LV_IMG_DECLARE(ui_img_light_png);    // assets/Light.png
LV_IMG_DECLARE(ui_img_airquality_png);    // assets/AirQuality.png
LV_IMG_DECLARE(ui_img_vector_png);    // assets/Vector.png
LV_IMG_DECLARE(ui_img_alight_png);    // assets/Alight.png
LV_IMG_DECLARE(ui_img_nowlight_png);    // assets/NowLight.png
LV_IMG_DECLARE(ui_img_rectangle_71_png);    // assets/Rectangle 71.png
LV_IMG_DECLARE(ui_img_group_64_png);    // assets/Group 64.png
LV_IMG_DECLARE(ui_img_1light_png);    // assets/1LIGHT.png
LV_IMG_DECLARE(ui_img_curtain_png);    // assets/Curtain.png
LV_IMG_DECLARE(ui_img_group_39_png);    // assets/Group 39.png



LV_FONT_DECLARE(ui_font_Font1);
LV_FONT_DECLARE(ui_font_Font2);
LV_FONT_DECLARE(ui_font_Font3);
LV_FONT_DECLARE(ui_font_jiajian);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
